const { v4: uuidV4} = require('uuid')

module.exports = [
    {
        id: uuidV4(),
        item: "income",
        amount: "3500",
        date: "May 12",
        from: 'Yanako Lajara',
        category: 'income',
    },
    {
        id: uuidV4(),
        item: "Coffee",
        amount: "-6",
        date: "May 15",
        from: 'Yanako Lajara',
        category: 'food',
    },
    {
        id: uuidV4(),
        item: "Saving",
        amount: "250",
        date: "May 24",
        from: 'Yanako Lajara',
        category: 'savings',
    },
    {
        id: uuidV4(),
        item: "Credit Card Payment",
        amount: "-125",
        date: "May 25",
        from: 'Yanako Lajara',
        category: 'bill',
    },
    {
        id: uuidV4(),
        item: "Groceries",
        amount: "-116",
        date: "Jun 03",
        from: 'Luz',
        category: 'food',
    },
    {
        id: uuidV4(),
        item: "Groceries",
        amount: "-116",
        date: "Jun 03",
        from: 'Luz',
        category: 'food',
    },
    {
        id: uuidV4(),
        item: "Income",
        amount: "1300",
        date: "Jun 05",
        from: 'Yanako',
        category: 'income',
    },
    {
        id: uuidV4(),
        item: "Pet expenses",
        amount: "-85",
        date: "Jun 08",
        from: 'Luz',
        category: 'pet',
    },
]